version: '3'
services:
    mongo:
        container_name: mongo_battleship
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: battle123root

    battleship_backend:
        container_name: battleship_backend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        volumes:
          - ./:/src
volumes:
  mongo:
